#!/bin/bash

# Check if PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
  echo "Error: PYFILE environment variable is not set."
  exit 1
fi

# Extract filename and extension
filename=$(basename -- "$PYFILE")
extension="${filename##*.}"

# Check if the file has a .py extension
if [ "$extension" != "py" ]; then
  echo "Error: The specified file is not a Python script (doesn't have a .py extension)."
  exit 1
fi

# Compile the Python script
output_filename="${filename%.*}.pyc"
python3 -m py_compile "$PYFILE"

# Check if compilation was successful
if [ $? -eq 0 ]; then
  echo "Compiling $PYFILE ..."
  mv "__pycache__/$filename" "$output_filename"
  rm -rf "__pycache__"
  echo "Compilation successful. Output filename: $output_filename"
else
  echo "Error: Compilation failed."
  exit 1
fi